FROM openjdk:17-jdk

ARG DB_URL
ARG DB_USER
ARG DB_PASS
ARG REDIS_HOST
ARG REDIS_PASS
ARG REDIS_PORT
ARG JOIN_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REDIRECT_URI
ARG KAKAO_CLIENT_ID
ARG KAKAO_REDIRECT_URI
ARG NCP_ACCESS_KEY
ARG NCP_SECRET_KEY
ARG BUCKET_NAME
ARG IP
ARG DEFAULT_PROFILE_IMG

ENV DB_URL=$DB_URL
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PASS=$REDIS_PASS
ENV REDIS_PORT=$REDIS_PORT
ENV JOIN_SECRET=$JOIN_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI
ENV KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
ENV KAKAO_REDIRECT_URI=$KAKAO_REDIRECT_URI
ENV NCP_ACCESS_KEY=$NCP_ACCESS_KEY
ENV NCP_SECRET_KEY=$NCP_SECRET_KEY
ENV BUCKET_NAME=$BUCKET_NAME
ENV IP=$IP
ENV DEFAULT_PROFILE_IMG=$DEFAULT_PROFILE_IMG


COPY build/libs/*.jar docker-springboot.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=docker", "-jar", "docker-springboot.jar"]
EXPOSE 8080