spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  profiles:
    active: local
    include: oauth, app
  cloud:
    aws:
      s3:
        endpoint: https://kr.object.ncloudstorage.com
        bucket: ${BUCKET_NAME}
      stack:
        auto: false
      region:
        static: ap-northeast-2
      credentials:
        accessKey: ${NCP_ACCESS_KEY}
        secretKey: ${NCP_SECRET_KEY}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server:
  tomcat:
    max-http-form-post-size: 104857600