spring:
  security:
    oauth2:
      client:
        registration:
          GOOGLE:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: email, profile

          KAKAO:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
#
#          naver:
#            client-id: {client-id}
#            client-secret: {client-secret}
#            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
#            authorization-grant-type: authorization_code
#            scope: name, email, profile_image
#            client-name: Naver

        provider:
          KAKAO:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
#          naver:
#            authorization_uri: https://nid.naver.com/oauth2.0/authorize
#            token_uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user_name_attribute: response